name: CI/CD

on:
  push:
    run: npm install

    - name: Run Tests
      run: npm test

  CD: 
    name: Continuous Delivery
    runs-on: ubuntu-latest

    needs: CI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3